    export const TASK_ACTIONS = {

        CREATE_TASK:"CREATE_TASK",
        DELETE_TASK:"DELETE_TASK",
        DELETE_ALL_TASK:"DELETEALL_TASK",
        HANDLE_TOGGLE_TASK:"HANDLE_TOGGLE_TASK",
        GET_COMPLETED_COUNT:"GET_COMPLETED_COUNT",
        COUNT_UNCOMPLETED_COUNT:"COUNT_UNCOMPLETED_COUNT",
    }